spring:
  # DB Configuration
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  mvc:
      view:
        # 页面默认前缀目录
        prefix: /WEB-INF/views/
        # 响应页面默认后缀
        suffix: .jsp

# mybatis Configuration
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  config-location: classpath:mybatis/SqlMapConfig.xml

server:
  port: 8080
  servlet:
    context-path: /layuidemo
